# Generated by Django 4.2 on 2023-05-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_año_fabricacion_carro_ano_fabricacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='ano_fabricacion',
            new_name='anio_fabricacion',
        ),
    ]
