# Generated by Django 4.1.7 on 2023-05-07 19:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_ano_fabricacion_carro_anio_fabricacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
