# Generated by Django 4.1.7 on 2023-05-07 19:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_carro_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
