# Generated by Django 4.2 on 2023-05-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_informacionextra_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacionextra',
            name='descripcion',
        ),
    ]
