# Generated by Django 4.1.7 on 2023-05-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_informacionextra_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionextra',
            name='descripcion',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
